In [4]:
import numpy as np

samples = ['The cat sat on the mat.',
           'The dog ate my work.']

token_index = {}
for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index)+1
token_index

{'The': 1,
 'cat': 2,
 'sat': 3,
 'on': 4,
 'the': 5,
 'mat.': 6,
 'dog': 7,
 'ate': 8,
 'my': 9,
 'work.': 10}

In [9]:
max_lenght = 10
results = np.zeros(shape=(len(samples),
                    max_lenght,
                    max(token_index.values()) + 1))

In [8]:
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_lenght]:
        index = token_index.get(word)
        results[i,j,index] = 1
results

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

In [16]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
sequences

[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]

In [22]:
from keras.layers import Embedding
emb_layer = Embedding(1000,64)

In [48]:
from keras.datasets import imdb
from keras import preprocessing

max_features = 10_000
maxlen = 40

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)


x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)

In [49]:
x_train, x_test

(array([[  22,   21,  134, ...,   19,  178,   32],
        [ 152,  491,   18, ...,   16,  145,   95],
        [  23,   22,   12, ...,    7,  129,  113],
        ...,
        [ 234, 2766,  234, ...,    4, 3586,    2],
        [  14,  123,    5, ...,   12,    9,   23],
        [1468,    2,  497, ...,  204,  131,    9]], dtype=int32),
 array([[  13,   92,  124, ...,   14,    6,  717],
        [   4,  529,   48, ...,  125,    4, 3077],
        [2321,   42, 1898, ...,    9,   57,  975],
        ...,
        [   4,  116,  218, ...,   21,  846, 5518],
        [ 985,  200,    5, ..., 2302,    7,  470],
        [  11,    4, 3567, ...,   34, 2005, 2643]], dtype=int32))

In [50]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding

model = Sequential()
model.add(Embedding(10000, 8, input_length=maxlen))
model.add(Flatten())

model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy',
                 metrics = ['acc'])
model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 40, 8)             80000     
_________________________________________________________________
flatten_2 (Flatten)          (None, 320)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 321       
Total params: 80,321
Trainable params: 80,321
Non-trainable params: 0
_________________________________________________________________


In [51]:
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.2)

/home/alexkay/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 1s 71us/step - loss: 0.6558 - acc: 0.6404 - val_loss: 0.5700 - val_acc: 0.7398
Epoch 2/10
20000/20000 [==============================] - 1s 65us/step - loss: 0.4775 - acc: 0.7926 - val_loss: 0.4586 - val_acc: 0.7790
Epoch 3/10
20000/20000 [==============================] - 1s 64us/step - loss: 0.3901 - acc: 0.8274 - val_loss: 0.4318 - val_acc: 0.7956
Epoch 4/10
20000/20000 [==============================] - 1s 66us/step - loss: 0.3508 - acc: 0.8455 - val_loss: 0.4249 - val_acc: 0.7982
Epoch 5/10
20000/20000 [==============================] - 1s 63us/step - loss: 0.3245 - acc: 0.8604 - val_loss: 0.4279 - val_acc: 0.7970
Epoch 6/10
20000/20000 [==============================] - 1s 67us/step - loss: 0.3034 - acc: 0.8726 - val_loss: 0.4304 - val_acc: 0.7960
Epoch 7/10
20000/20000 [==============================] - 1s 64us/step - loss: 0.2844 - acc: 0.8819 - val_loss: 0.4371 - val_acc:

In [47]:
history.plot()

AttributeError: 'History' object has no attribute 'plot'