In [9]:
from sympy import *
init_printing()
%matplotlib inline

In [10]:
#vars = var('x,y')
# foo = 2*x**2 - 3*x*y + 4*y**2 - 2*x + y + 10 
# diff(foo,x)

In [11]:
import numpy as np
X1 = np.array([0,1,2,3])
X2 = np.array([3,2,1,0])
Y = np.array([0,1,0,3])

X1 = np.vstack([X1, np.ones(len(X1))]).T
X2 = np.vstack([X2, np.ones(len(X2))]).T
print(X1)
print(X2)

[[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]]
[[3. 1.]
 [2. 1.]
 [1. 1.]
 [0. 1.]]


In [72]:
from sympy import *
init_printing()
%matplotlib inline
vars = var('w1, w2, w0')
L = (3*w2+w0-0)**2 + (w1+2*w2+w0-1)**2 + (2*w1+w2+w0-0)**2 + (3*w1+w0-3)**2 + w1**2 + w2**2 + w0**2
for var in vars:
    f = diff(L, var)
    print(pretty_print(f))

12⋅w₀ + 30⋅w₁ + 8⋅w₂ - 20
None
12⋅w₀ + 8⋅w₁ + 30⋅w₂ - 4
None
10⋅w₀ + 12⋅w₁ + 12⋅w₂ - 8
None


In [59]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x, y, z

system = Matrix(( (12, 30, 8, 20), (12, 8, 30, 4), (0, 12, 12, 8)))
solve_linear_system(system)

In [58]:
from sympy.solvers.solvers import solve_linear_system_LU
# solve_linear_system_LU(Matrix([
#     [12, 28, 8, 20],
#     [12, 8, 28, 4],
#     [8, 12, 12, 8]]),[x, y, z])

ans = solve_linear_system_LU(Matrix([
[12, 30, 8, 20],
[12, 8, 30, 4],
[10, 12, 12, 8]]), [w1, w2, w0])
ans

In [60]:
import numpy as np

x = np.array([[10,12,12], [12,30,8], [12,8,30]])
y = np.array([8,20,4])
np.linalg.solve(x,y)

array([ 0.17391304,  0.62450593, -0.1027668 ])

In [48]:
from sklearn.linear_model import Ridge
import numpy as np

alpha=1.0

X = np.array( [ [0,3], [1,2], [2,1], [3,0] ] )
y = np.array( [ 0, 1, 0, 3 ] )

#expand X by 1.0 column

X = np.insert(X, 0, values=1, axis=1 )

model = Ridge(alpha=alpha, fit_intercept=False )
model.fit(X, y )

print("coef:", model.coef_);

coef: [ 0.17391304  0.62450593 -0.1027668 ]
